- name: Start and maintain database
  hosts: localhost
  tasks:

  - name: Ansible hello world
    ansible.builtin.debug:
      msg: Hello from ansible in down.yaml
  - name: Dump data for migration
    ansible.builtin.shell: |
      mysqldump -u flyway_user -pSecret5555 -h 127.0.0.1 --no-create-info subscriber_db subscribers > migrations/V2__seed_data.sql
    args:
      creates: migrations/V2__seed_data.sql
  - name: stop mysql
    ansible.builtin.shell: sudo service mysql stop > /tmp/mysqldown.txt
    args:
      creates: /tmp/mysqldown.txt
  - name: Remove mysql.txt file (delete file)
    ansible.builtin.file:
      path: /tmp/mysql.txt
      state: absent
  - name: Run Flyway migrations
    ansible.builtin.shell: flyway -configFiles=flyway.conf migrate
    args:
      creates: /tmp/flyway_migrated.txt

  - name: Mark flyway migration as done
    ansible.builtin.file:
      path: /tmp/flyway_migrated.txt
      state: touch
