- name: Start and maintain database
  hosts: localhost
  tasks:
  - name: Remove mysql.txt file (delete file)
    ansible.builtin.file:
      path: /tmp/mysqldown.txt
      state: absent

  - name: Ansible hello world
    ansible.builtin.debug:
      msg: Hello from ansible in up.yaml
  - name: start mysql
    ansible.builtin.shell: sudo service mysql start > /tmp/mysql.txt
    args:
      creates: /tmp/mysql.txt
  - name: created database
    ansible.builtin.shell: sudo mysql -u root < migrations/createdb.sql && mv migrations/createdb.sql migrations/finished
    args:
      creates: migrations/finished/createdb.sql

  - name: Run Flyway migrations
    ansible.builtin.shell: flyway -configFiles=flyway.conf migrate
    args:
      creates: /tmp/flyway_migrated.txt

  - name: Mark flyway migration as done
    ansible.builtin.file:
      path: /tmp/flyway_migrated.txt
      state: touch
